#!/bin/bash
echo "\"(Ôo) > 1-confused_smiley
echo -e '#!/bin/bash
cat /etc/passwd' > 2-hellofile
echo -e '#!/bin/bash
cat /etc/passwd /etc/hosts' > 3-twofiles
echo -e '#!/bin/bash
tail /etc/passwd' > 4-lastlines
echo -e '#!/bin/bash
head /etc/passwd' > 5-firstlines
echo -e '#!/bin/bash
head -n 3 iacta | tail -n 1' > 6-third_line
echo -e '#!/bin/bash
echo Best School > \*\\"Best School"\'\\*$\?\*\*\*\*\*:)"
